apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # replica set lables
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
        component: mongodb
        project: roboshop
        tier: database
  # this is pod defination
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mongodb
          image: lakshmi315/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
      component: mongodb
      project: roboshop
      tier: database
spec:
  selector:
      component: mongodb
      project: roboshop
      tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # nginx port